config/routes.rb
PaymentsTracker::Engine.routes.draw do
  root :to => 'payment_items#index'

  resources :payment_items
end

app/controllers/payments_tracker/application_controller.rb
# This controller must inherit from the main application
class PaymentsTracker::ApplicationController < ApplicationController
end

app/controllers/payments_tracker/payment_items_controller.rb
require_dependency "payments_tracker/application_controller"

module PaymentsTracker
  class PaymentItemsController < ApplicationController

    def index
      @payment_items = PaymentItem.all
    end

    def new
      @payment_item = get_class.new
    end

    private 

    def get_class
      @@item_classes ||= {}
      return @@item_classes[params[:kind]] if @@item_classes.has_key? params[:kind]

      @@namespace ||= self.class.name.split('::').first
      @@base_class ||= controller_name.classify

      @@item_classes[params[:kind]] = "#{@@namespace}::#{params[:kind].capitalize}#{@@base_class}".constantize
    end

  end
end

app/controllers/payments_tracker/payments_controller.rb
require_dependency "payments_tracker/application_controller"

module PaymentsTracker
  class PaymentsController < ApplicationController
    def index
    end
  end
end

app/views/payments_tracker/payment_items/_general_amounts.html.haml
#{number_to_currency(item.per_pupil_amount)} per pupil

app/views/payments_tracker/payment_items/_payment_items_table.html.haml
- @payment_items ||= []
%table#payment_items_table_datatable.datatable.table-striped.table-bordered.table-condensed
  %thead
    %tr
      %th
        = t('payments_tracker.activerecord.attributes.payment_item.title')
      %th
        = t('payments_tracker.activerecord.attributes.payment_item.owner')
      %th
        = t('payments_tracker.activerecord.attributes.payment_item.grouping')
      %th
        = t('payments_tracker.activerecord.attributes.payment_item.expires')
      %th
        = t('payments_tracker.activerecord.attributes.payment_item.due')
      %th
        = t('payments_tracker.activerecord.attributes.payment_item.type')
      %th
        = t('payments_tracker.activerecord.attributes.payment_item.amount')
      %th
        = t('payments_tracker.status')
      %th.action

  %tbody
    - @payment_items.each do |item|
      %tr
        %td= item.title
        %td= item.owner.name
        %td= item.grouping.name
        %td= distance_of_time_in_words_to_now(item.expires_at) unless item.expires_at.nil?
        %td= distance_of_time_in_words_to_now(item.due_at) unless item.due_at.nil?
        %td= item.type_name
        %td= render "#{item.type_name.downcase}_amounts", :item => item
        %td
          - if item.closed?
            = t('payments_tracker.closed')
          - else
            = t('payments_tracker.open')
        %td

app/views/payments_tracker/payment_items/index.html.haml
%h1.no_print
  = t('payments_tracker.payment_items')
  = link_to t("general.actions.print"), "#", :id => "print_index_button", :class => "btn no_print"

.sub_section.payment_item_filters.no_print
  %h2= t('general.actions.filter')
  %form{:method => :get}
    .form_content
      .field.filter
        = label_tag 'all', t('payments_tracker.all_items')
        = radio_button_tag 'filter', 'all', @filter == 'all', {:checked => "checked"}
        = label_tag 'general', t('payments_tracker.general_items')
        = radio_button_tag 'filter', 'general', @filter == 'general'
        = label_tag 'multiple', t('payments_tracker.multiple_items')
        = radio_button_tag 'filter', 'multiple', @filter == 'multiple'
        = label_tag 'open', t('payments_tracker.open_items')
        = radio_button_tag 'filter', 'open', @filter == 'open'

= render 'payment_items_table'

.links
  = link_to t("payments_tracker.payment_item.new_general"), new_payment_item_path(:kind => 'general'), :class => "btn primary", :id => "create_new"

app/views/payments_tracker/payment_items/new.html.haml
%h1 
  = t("payments_tracker.payment_item.new_#{params[:kind]}")

  .btn.no_print#save_button{:title => t("general.actions.save")}
  .btn.no_print#cancel_button{:title => t("general.actions.cancel")}

= render 'form'

.links
  = link_to t("general.actions.back"), payment_items_path